server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: JQube API Server
  config:
    import: optional:file:.env[.properties]
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

client:
    url: ${CLIENT_URL}

github:
  oauth:
    client-id: ${GITHUB_OAUTH_CLIENT_ID}
    client-secret: ${GITHUB_OAUTH_CLIENT_SECRET}
    redirect-uri: ${GITHUB_REDIRECT_URI}


security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 86400000

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
    doc-expansion: none

  packages-to-scan: net.jqube.server.controllers
  paths-to-match:
    - /api/**
