package net.jqube.server.enums;

public enum QubeAuthorities {

    VIEW_QUBE,
    UPDATE_QUBE,
    DELETE_QUBE,
    ARCHIVE_QUBE,

    VIEW_MEMBERS,
    INVITE_MEMBER,
    REMOVE_MEMBER,
    CHANGE_MEMBER_ROLE,

    VIEW_REPOSITORY,
    SYNC_REPOSITORY,

    START_SCAN,
    CANCEL_SCAN,
    VIEW_SCANS,

    VIEW_FINDINGS,
    CHANGE_FINDING_STATUS,

    GENERATE_REMEDIATION,
    CREATE_PULL_REQUEST,

    MANAGE_WEBHOOKS,

    MANAGE_SETTINGS
}
